### ISSUE TITLE
Update to 6.0.7

### ISSUE THREAD

**Issue by OndrejIT** [r4dh4l/seafile-client-rpi#4]
Its posible update to Actual version?
https://manual.seafile.com/changelog/client-changelog.html
6.0.7 (2017/06/23)

**Comment by saljut7** [comment]
HI, last time compilation failed but give me some hours. I will try it again...

**Comment by saljut7** [comment]
Sorry, failed compiling 6.0.7 in last step: https://forum.seafile.com/t/install-seafile-cli-client-on-raspberry-pi/778/17?u=saljut7

Have to ask the devs for help. Meanwhile try 6.0.0 - it works fine. Will report if I figured out the problem.

**Comment by mindcont** [comment]
Hi, guys
I have compiled seafile-client gui and seafile-cli for two versions of the Raspbian system Jessie and stretch, you can download at [http://t.cn/RmtFlMZ](http://t.cn/RmtFlMZ).

```css
# For stretch version, the jessie same too.
sudo dpkg -i libsearpc-3.0.0-1_armhf_rpi_stretch.deb
sudo dpkg -i ccnet_6.1.1-1_armhf_rpi_stretch.deb
sudo dpkg -i seafile_6.1.1-1_armhf_rpi_stretch.deb # seafile-cli, the command seafile client
sudo dpkg -i seafile-client_6.1.1-1_armhf_rpi_stretch.deb # seafile-client gui
```

For compile install way, you can visit [stackexchange](https://raspberrypi.stackexchange.com/questions/41803/how-to-install-seafile-client/41857#41857?newreg=7d71d5742be74643a905debff630a6f5).

![2018-04-08-212428_1360x768_scrot](https://user-images.githubusercontent.com/13744152/38468182-2c97c3e2-3b75-11e8-954e-87756c292457.png)

enjoy it~
