### ISSUE TITLE
Failed to init ccnet

### ISSUE THREAD

**Issue by StefanDesu** [r4dh4l/seafile-client-rpi#5]
Hi,

I wanted to install the Seafile client on my Raspberry Pi (version 1 model B), but no matter what I do, I can't initialize it ("seaf-cli init -d ~/seafile-client" always outputs "Failed to init ccnet", if I try ccnet-init manually, it says "Illegal instruction"). I tried to install every dependency that might be necessary, but no luck. I'm also not sure how to properly debug this as I can't find any log files for ccnet or seafile. Any ideas what the problem might be?

I'm using the latest Raspbian version, freshly installed yesterday via NOOBS.

Thanks!
Stefan

**Comment by saljut7** [comment]
Hi @StefanDesu 

just to confirm: you followed my installation guide under https://github.com/saljut7/seafile-client-rpi ?

**Comment by StefanDesu** [comment]
Hi @saljut7 

yes, I followed the guide step by step for the CLI only client without any problems. All the binaries and commands seem to be properly installed. Then I continued with the official Seafile CLI guide linked at the bottom of your guide and got the error when executing `seaf-cli init -d ~/seafile-client`. I tried to Google the error, but couldn't find much, so I thought that maybe some dependency was missing for ccnet, but it didn't fix the problem even after uninstalling and reinstalling the client (following your guide again).

It seems to be a very specific problem to my setup, although that's weird because there's nothing special about my Raspbian installation. If you have any ideas, I'd be glad to try them out!

**Comment by saljut7** [comment]
Hm... well I can not rule out that there may be problems using my packages because I didn't compile these ones on a Raspberry Pi. If it is not urgent: I try to compile the latest client at the moment under Raspbian with same Pi model you are using. If you could wait a little bit more I would come back to you when finished.

**Comment by StefanDesu** [comment]
I'm in not rush at all, so that would be awesome! If I can help in any way, please let me.

**Comment by saljut7** [comment]
At the moment even compiling of libsearpc fails on my RPi2 in a way that the compiled DEB doesn't install anything. Will need a while to figure out what's wrong here... sry will need more time, no eta. :/

**Comment by gufertum** [comment]
I have the exact same problem but installed on a freshly set up RPi1 (raspbian)

**Comment by saljut7** [comment]
Meanwhile I migrated to a x86-64 server. Unfortunately I have not time debugging this anymore. Sry. :/

**Comment by r4dh4l** [comment]
try https://github.com/r4dh4l/seafile-client-rpi/issues/4#issuecomment-379551378
